import type { KnowledgeItem } from "../../domain/card";
import { defineTenant } from "../defineTenant";

const assetBase = import.meta.env.BASE_URL.replace(/\/?$/, "/");
const assets = (fileName: string) =>
  `${assetBase}tenants/template/assets/${fileName}`;

const source = "通用模板说明";

const knowledgeBase: KnowledgeItem[] = [
  {
    id: "materials",
    question: "制作企业数智名片需要哪些资料？",
    shortQuestion: "需要哪些资料？",
    answer:
      "建议准备企业主体与品牌资料、业务与产品说明、可公开的案例和数据、官方联系渠道，以及常见问题。资质、客户名称、业绩数字和人物素材需要同时提供可核验来源与使用授权。",
    keywords: ["资料", "清单", "准备", "文档", "素材", "制作"],
    source,
  },
  {
    id: "adaptation",
    question: "这套模板能适配任何企业吗？",
    shortQuestion: "任何企业都能用吗？",
    answer:
      "大多数企业可以复用这套内容结构，但不能直接复制示例文案。每家企业都需要重新整理品牌、业务、证据、联系入口和问答边界。医疗、金融、法律、教育等行业还需要增加相应的合规审核。",
    keywords: ["任何企业", "适配", "行业", "通用", "复用", "企业"],
    source,
  },
  {
    id: "missing",
    question: "企业资料不完整时怎么办？",
    shortQuestion: "资料不全怎么办？",
    answer:
      "可以先生成内部预览，但缺失内容必须明确标记为待补充。模板不会自动编造联系方式、资质、客户、案例、价格或经营数据，相关区域应在审核完成前隐藏或保留占位提示。",
    keywords: ["缺失", "不完整", "资料不全", "待补充", "占位", "编造"],
    source,
  },
  {
    id: "safety",
    question: "发布前需要做哪些安全审核？",
    shortQuestion: "怎么做安全审核？",
    answer:
      "至少需要核对企业主体、品牌与素材授权、数据口径、案例公开权限、联系人授权、隐私信息和行业限制。资料助手还应配置禁答边界，避免输出未确认事实、敏感信息或结果承诺。",
    keywords: ["安全", "审核", "合规", "授权", "隐私", "禁答"],
    source,
  },
  {
    id: "onboarding",
    question: "一家新企业如何接入？",
    shortQuestion: "新企业怎么接入？",
    answer:
      "新企业接入通常包括资料收集、事实整理、页面与知识库配置、企业审核、内部预览和正式发布。后续资料发生变化时，应通过新版本更新并保留审核记录。",
    keywords: ["接入", "新企业", "流程", "上线", "发布", "版本"],
    source,
  },
];

export const templateTenant = defineTenant({
  id: "template",
  version: "2026.07-template-v1",
  seo: {
    title: "企业数智名片通用模板 | 内容结构示意",
    description: "用于演示企业资料导入、事实审核、页面生成与知识问答结构的通用模板。",
  },
  brand: {
    name: "企业数智名片通用模板",
    shortName: "通用模板",
    tagline: "先搭骨架，再装入企业事实",
    headerDescriptor: "占位内容 · 接入后替换",
    logo: {
      src: assets("template-mark.webp"),
      alt: "企业数智名片通用模板图形标记",
      width: 432,
      height: 432,
    },
    homeAriaLabel: "返回企业数智名片通用模板首页",
    officialAction: {
      kind: "external",
      label: "官网占位",
      target: "https://example.com",
    },
  },
  theme: {
    defaultMode: "system",
    action: "#d85a2b",
    onAction: "#180a06",
    light: {
      accent: "#a33d1b",
      accentStrong: "#7f2f15",
      accentSoft: "rgba(163, 61, 27, 0.12)",
      background: "#eef1f2",
      surface: "#fafbfb",
      surfaceRaised: "#f4f6f6",
      surfaceMuted: "#e3e8e9",
      text: "#172027",
      textSoft: "#4d5b63",
      textFaint: "#637178",
      line: "rgba(23, 32, 39, 0.14)",
      lineStrong: "rgba(23, 32, 39, 0.25)",
      shadow: "0 28px 80px rgba(37, 47, 52, 0.13)",
    },
    dark: {
      accent: "#f0794d",
      accentStrong: "#ff9a74",
      accentSoft: "rgba(240, 121, 77, 0.13)",
      background: "#0d1317",
      surface: "#151d22",
      surfaceRaised: "#1c262c",
      surfaceMuted: "#242f35",
      text: "#f3f6f6",
      textSoft: "#b1bdc2",
      textFaint: "#8c9aa1",
      line: "rgba(226, 235, 238, 0.15)",
      lineStrong: "rgba(226, 235, 238, 0.26)",
      shadow: "0 28px 90px rgba(0, 0, 0, 0.36)",
    },
    heroOverlay: {
      light: "rgba(238, 241, 242, 0.16)",
      dark: "rgba(8, 12, 15, 0.32)",
    },
    radiusCard: "24px",
    radiusControl: "999px",
    radiusSmall: "12px",
  },
  hero: {
    id: "top",
    kicker: "通用企业内容模板 · 非真实企业页面",
    titleLines: ["先建立通用能力", "再装入企业资料"],
    summary: "这是一份结构与交互示意，所有企业事实都需在接入后替换并审核。",
    art: {
      src: assets("template-hero.webp"),
      alt: "抽象的企业资料模块与审核流程示意图",
      width: 1672,
      height: 941,
    },
    actions: [
      { kind: "anchor", label: "查看内容结构", target: "#capabilities" },
      { kind: "anchor", label: "查看接入流程", target: "#onboarding" },
    ],
    metrics: [
      { value: "4 类", label: "建议输入资料", note: "主体、业务、证据、联系" },
      { value: "7 类", label: "页面内容模块", note: "本页全部提供示意" },
      { value: "5 条", label: "边界问答示例", note: "均来自模板说明" },
      { value: "1 轮+", label: "企业发布审核", note: "正式上线前必须完成" },
    ],
  },
  sections: [
    {
      type: "feature-grid",
      id: "capabilities",
      navLabel: "结构",
      showInNav: true,
      eyebrow: "通用内容骨架",
      heading: "先把企业需要表达的内容分清楚",
      description: "以下四类内容都是占位结构，接入企业后必须替换为已核验资料。",
      businesses: [
        {
          icon: "buildings",
          eyebrow: "企业身份",
          title: "主体与品牌",
          description: "说明企业是谁、服务谁，以及可以公开使用的品牌表达。",
          status: "等待企业资料",
          points: ["主体名称", "品牌定位", "资质范围", "公开联系渠道"],
        },
        {
          icon: "globe",
          eyebrow: "业务表达",
          title: "产品与服务",
          description: "把复杂业务整理成访客能快速理解的价值、场景与边界。",
          status: "等待业务确认",
          points: ["核心业务", "目标客户", "应用场景", "服务边界"],
        },
        {
          icon: "book",
          eyebrow: "可信证据",
          title: "案例与数据",
          description: "仅展示经过企业确认并具备公开权限的案例和统计口径。",
          status: "等待证据审核",
          points: ["案例授权", "数据来源", "统计日期", "引用说明"],
        },
        {
          icon: "path",
          eyebrow: "访客转化",
          title: "联系与行动",
          description: "根据访客意图提供明确入口，同时控制隐私和承诺边界。",
          status: "等待渠道配置",
          points: ["商务咨询", "产品体验", "资料下载", "人工服务"],
        },
      ],
    },
    {
      type: "media-showcase",
      id: "content-kit",
      navLabel: "资料",
      showInNav: true,
      heading: "让分散资料变成可审核的内容包",
      description: "系统可以整理文档和公开页面，但事实确认与发布授权仍由企业负责。",
      capabilities: [
        { icon: "book", title: "资料导入", description: "汇集介绍文档、官网内容、图片和问答" },
        { icon: "path", title: "事实分层", description: "区分已确认、待确认和禁止公开内容" },
        { icon: "code", title: "页面配置", description: "把内容装入通用模块和企业主题" },
        { icon: "student", title: "知识问答", description: "建立资料内回答与拒答边界" },
      ],
      action: {
        kind: "assistant",
        label: "查询资料清单",
        target: "制作企业数智名片需要哪些资料？",
      },
      visualLabel: "通用示意图",
      visualTitle: "企业内容包结构示意",
      visual: {
        src: assets("template-content-kit.webp"),
        alt: "由企业身份、业务、证据和问答组成的内容包示意",
        caption: "此图仅用于解释通用结构，不含任何真实企业资料。",
        width: 1599,
        height: 900,
      },
    },
    {
      type: "process",
      id: "workflow",
      navLabel: "流程",
      showInNav: true,
      heading: "生成页面之前，先走完四个步骤",
      description: "自动整理提高效率，企业确认保证真实性，版本记录保证后续可维护。",
      steps: [
        { title: "收集", text: "接收企业授权提供的资料和公开来源。" },
        { title: "整理", text: "提取可展示事实、待确认项与禁答边界。" },
        { title: "审核", text: "由企业负责人核对文案、数据、素材和链接。" },
        { title: "发布", text: "通过审核后生成企业专属页面与知识库。" },
      ],
      audienceHeading: "需要共同确认的四类角色",
      audiences: [
        { icon: "buildings", title: "品牌负责人", description: "确认品牌口径与视觉授权。" },
        { icon: "globe", title: "业务负责人", description: "确认产品、场景与服务边界。" },
        { icon: "book", title: "法务与安全", description: "确认合规、隐私和公开权限。" },
        { icon: "users", title: "销售与服务", description: "确认联系入口与线索承接方式。" },
      ],
    },
    {
      type: "evidence",
      id: "review",
      navLabel: "审核",
      showInNav: true,
      heading: "未确认的内容，不进入正式页面",
      description: "模板用审核清单代替猜测，避免把占位信息误当成企业事实。",
      visual: {
        src: assets("template-review.webp"),
        alt: "企业页面发布前的事实、授权与安全审核清单示意",
        caption: "审核图为通用流程示意，不代表任何真实企业已经通过审核。",
        width: 1599,
        height: 900,
      },
      headlineMetric: "先审核",
      metricDescription: "未确认事实保留为待补充，不进入正式发布",
      themesAriaLabel: "发布前审核范围",
      themes: ["主体与资质", "数据与案例", "素材与肖像", "联系与承诺"],
      caveat: "本页仅演示结构，不代表任何真实企业、资质、业绩或合作承诺。",
      supportHeading: "通用可信来源",
      supportNote: "每家企业接入时重新建立",
      supportNames: ["企业授权资料", "公开官网信息", "审核确认记录", "版本变更记录"],
    },
    {
      type: "engagement",
      id: "onboarding",
      navLabel: "接入",
      showInNav: true,
      heading: "四步生成一份企业专属配置",
      description: "页面能力保持通用，企业事实、视觉、问答和联系入口按租户独立配置。",
      steps: [
        { title: "建立租户", text: "创建独立企业标识、素材目录和配置版本。" },
        { title: "装入资料", text: "填入已确认的品牌、业务、证据和问答。" },
        { title: "企业验收", text: "预览桌面与移动页面并完成内容终审。" },
        { title: "独立发布", text: "通过企业路径或域名访问专属数智名片。" },
      ],
      cta: {
        title: "先了解接入边界与所需资料",
        description: "模板只提供结构，新企业资料必须单独审核和配置。",
        action: {
          kind: "assistant",
          label: "了解新企业接入",
          target: "一家新企业如何接入？",
        },
      },
    },
    {
      type: "faq",
      id: "faq",
      navLabel: "FAQ",
      showInNav: true,
      eyebrow: "通用问答",
      heading: "先说明模板能做什么，不能替企业确认什么",
      description: "所有回答仅解释通用流程，不包含任何真实企业事实。",
      itemIds: ["materials", "adaptation", "missing", "safety", "onboarding"],
    },
    {
      type: "closing",
      id: "closing",
      navLabel: "完成",
      showInNav: false,
      heading: "通用能力已经就位，下一步是装入真实且获授权的企业资料",
      description: "当前页面是可运行模板，不是任何企业的正式官网或业务承诺。",
      art: {
        src: assets("template-hero.webp"),
        alt: "企业资料从模板进入专属页面的抽象示意",
        width: 1672,
        height: 941,
      },
      actions: [
        { kind: "assistant", label: "检查发布风险", target: "发布前需要做哪些安全审核？" },
      ],
    },
  ],
  assistant: {
    title: "通用模板资料助手",
    status: "示意",
    subtitle: "本地模板知识库 · 不代表任何企业",
    launcherAriaLabel: "打开通用模板资料助手",
    launcherKicker: "只回答模板说明",
    launcherLabel: "问资料助手",
    initialMessage: {
      text: "你好，我是通用模板资料助手。我只解释企业资料接入、审核和发布流程，不提供任何真实企业信息。",
      source,
    },
    quickQuestionIds: ["materials", "adaptation", "onboarding"],
    labels: {
      closeBackdrop: "关闭资料助手",
      closeButton: "关闭助手",
      quickQuestions: "模板常见问题",
      quickQuestionsIntro: "可以先问",
      loading: "正在检索模板说明",
      input: "向模板资料助手提问",
      placeholder: "问资料、审核或企业接入",
      send: "发送问题",
      sourcePrefix: "来源：",
    },
    disclaimer: "回答仅来自通用模板说明，不构成任何企业事实或承诺。",
    knowledgeBase,
    fallback: {
      answer: "通用模板说明暂未覆盖这个问题，我不会补充未经企业确认的信息。请先完善资料清单，或交由企业负责人审核。",
      source,
    },
  },
  presentation: {
    heroVisual: {
      src: assets("card-ui/enterprise-city-1600.webp"),
      srcSet: `${assets("card-ui/enterprise-city-800.webp")} 800w, ${assets("card-ui/enterprise-city-1600.webp")} 1600w`,
      sizes: "(max-width: 480px) 100vw, 480px",
      alt: "企业数智名片通用城市科技场景",
      width: 1600,
      height: 1200,
    },
    heroSummary: "统一展示企业身份、业务能力、可信案例和合作入口，正式发布内容以企业审核资料为准。",
    solutions: [
      {
        id: "company-profile",
        title: "企业资料展示",
        description: "集中呈现企业定位、核心能力与服务范围。",
      },
      {
        id: "products-and-cases",
        title: "产品与案例",
        description: "展示企业已审核发布的产品、服务与实践案例。",
      },
      {
        id: "ai-reception",
        title: "AI 智能接待",
        description: "基于企业已发布知识回答问题并承接合作需求。",
      },
    ],
    caseStudy: {
      title: "企业案例待发布",
      category: "通用模板",
      description: "企业审核并发布案例后，这里将自动展示真实案例内容。",
      detail: "通用模板不提供虚构案例。请在后台录入具备公开授权的案例背景、实施方案、结果和图片，发布后即可自动替换本区域。",
      visual: {
        src: assets("template-review.webp"),
        alt: "企业案例发布前的资料审核示意",
        width: 1599,
        height: 900,
      },
    },
    owner: {
      demoLabel: "演示资料，待替换",
      name: "个人姓名",
      role: "职务 / 岗位",
      summary: "介绍个人负责的业务、专业方向与可以公开的合作范围。",
      valueProposition: "以真实资料建立信任，用专业能力推动合作落地。",
      capabilities: ["专业能力", "业务协同", "客户服务"],
      experiences: [
        {
          period: "20XX - 至今",
          organization: "当前企业",
          role: "当前职务",
          description: "填写当前负责的业务与工作范围。",
        },
        {
          period: "20XX - 20XX",
          organization: "过往企业 A",
          role: "过往职务",
          description: "填写经本人确认并允许公开的职业经历。",
        },
        {
          period: "20XX - 20XX",
          organization: "过往企业 B",
          role: "过往职务",
          description: "未获授权的信息保持隐藏或占位。",
        },
      ],
      portrait: {
        src: assets("card-ui/demo-owner-1024.webp"),
        srcSet: `${assets("card-ui/demo-owner-512.webp")} 512w, ${assets("card-ui/demo-owner-1024.webp")} 1024w`,
        sizes: "(max-width: 480px) 44vw, 210px",
        alt: "通用模板的演示商务人物形象",
        width: 1024,
        height: 1280,
      },
    },
    assistantVisual: {
      src: assets("card-ui/ai-assistant-1200.webp"),
      srcSet: `${assets("card-ui/ai-assistant-600.webp")} 600w, ${assets("card-ui/ai-assistant-1200.webp")} 1200w`,
      sizes: "(max-width: 480px) 52vw, 250px",
      alt: "企业数智名片通用 AI 助手形象",
      width: 1200,
      height: 1200,
    },
    assistantQuestionIds: ["materials", "adaptation", "missing", "safety", "onboarding"],
    assistantRecommendations: [
      {
        title: "企业资料清单",
        description: "了解制作企业数智名片需要准备的资料。",
        question: "制作企业数智名片需要哪些资料？",
      },
      {
        title: "内容审核",
        description: "了解正式发布前需要确认的事实与授权。",
        question: "发布前需要做哪些安全审核？",
      },
      {
        title: "新企业接入",
        description: "了解从资料收集到正式发布的完整流程。",
        question: "一家新企业如何接入？",
      },
    ],
  },
  footer: {
    brandNote: "企业数智名片通用模板 · 占位内容",
    disclaimer: "本页不是任何真实企业页面，所有品牌、业务、案例、数据和联系方式都需在接入后替换并审核。",
    backToTopAction: { kind: "anchor", label: "返回顶部", target: "#top" },
  },
});
