import type {
  CaseStudy,
  CompanyProfile,
  EnterpriseTemplateBlock,
  ManagedCard,
  Product,
  SelectableFaqDocument,
} from "../api/types";

import tuozheHackathonUrl from "../../../card-web/public/tenants/tuotu/assets/hackathon-group.webp";
import tuozheHeroUrl from "../../../card-web/public/tenants/tuotu/assets/hero-ecosystem.webp";
import tuozhePlatformUrl from "../../../card-web/public/tenants/tuotu/assets/platform-events.webp";
import tuozheLogoUrl from "../../../card-web/public/tenants/tuotu/assets/tuotu-logo.webp";

export const tuozheCard: ManagedCard = {
  id: "local-tuozhe-card",
  cardKind: "enterprise",
  slug: "tuozhe-ai-ecosystem",
  displayName: "拓浙AI生态",
  title: "连接人才、技术与真实产业",
  avatarUrl: tuozheLogoUrl,
  assistantName: "拓浙 AI 资料助手",
  welcomeMessage: "你好，我可以介绍拓浙的活动、AI 社区、项目实践、浙客松与合作方式。",
  suggestedQuestions: [
    "学生可以怎样参与拓浙？",
    "企业可以怎样发起合作？",
    "浙客松是什么？",
  ],
  policyVersions: {
    privacy: "local-review",
    chatNotice: "local-review",
    leadConsent: "local-review",
  },
  identityTitles: ["AI 生态连接平台", "校园与产业共创"],
  identityPositioning: "连接学生、学院、企业与真实 AI 需求",
  identityTags: ["AI 社区", "项目实践", "浙客松"],
  contactFields: [
    {
      id: "website",
      kind: "website",
      label: "官方网站",
      value: "tuotuzju.com",
      href: "https://tuotuzju.com/",
    },
    {
      id: "email",
      kind: "email",
      label: "联系邮箱",
      value: "service@tuotuzju.com",
      href: "mailto:service@tuotuzju.com",
    },
    {
      id: "phone",
      kind: "phone",
      label: "联系电话",
      value: "0571-87950000",
      href: "tel:057187950000",
    },
  ],
  shareUrl: "",
  qrUrl: "",
  status: "draft",
  version: 1,
};

export const tuozheCompany: CompanyProfile = {
  id: "local-tuozhe-company",
  name: "拓浙AI生态",
  summary: "连接学生、学院、企业与真实 AI 需求，让机会、学习、项目、赛事和成果持续形成下一次合作。",
  industry: "人工智能生态与产学协作",
  region: "浙江",
  website: "https://tuotuzju.com/",
  logoUrl: tuozheLogoUrl,
  positioning: "从校园连接真实世界",
  profileFacts: [
    { id: "audience", label: "生态对象", value: "学生 · 学院 · 企业" },
    { id: "path", label: "协作路径", value: "学习 · 项目 · 赛事" },
    { id: "goal", label: "共同目标", value: "让人才成长，让项目落地" },
  ],
  profileTags: ["AI 社区", "跨学科共创", "产业协作"],
  profilePersonalizationPolicyVersion: "local-review",
  aiOffTopicAnswerMode: "limited",
  aiOffTopicQuestionLimit: 3,
  visitNotificationsEnabled: true,
  visitReportNotificationsEnabled: true,
  visitNotificationInAppEnabled: true,
  visitNotificationWecomEnabled: true,
  visitNotificationRecipientScope: "both",
  version: 1,
};

export const tuozheProducts: Product[] = [
  {
    id: "tuozhe-opportunities",
    slug: "opportunities",
    name: "机会与活动聚合",
    category: "拓途浙享",
    summary: "汇集讲座、竞赛、志愿、招新等校园机会，让信息先被看见。",
    detail: "拓途浙享作为生态的信息共享平台，持续发布活动与项目，并连接后续学习、组队和成果展示。",
    audience: "学生、学院与校园组织",
    priceBoundary: "以官网公开信息为准",
    imageUrl: tuozhePlatformUrl,
    visibility: "public",
    sortOrder: 0,
    settings: {},
    status: "published",
    version: 1,
  },
  {
    id: "tuozhe-community",
    slug: "ai-community",
    name: "AI 学习与项目社群",
    category: "人才成长",
    summary: "从基础内容、工具练习到项目陪跑，帮助成员完成第一个 AI 作品。",
    detail: "成员完成基础学习后，可以继续进入小型需求、浙客松或企业项目，在真实协作中积累作品与经验。",
    audience: "不同专业、不同基础的青年学习者",
    priceBoundary: "参与方式以当期活动说明为准",
    imageUrl: tuozheHeroUrl,
    visibility: "public",
    sortOrder: 1,
    settings: {},
    status: "published",
    version: 1,
  },
  {
    id: "tuozhe-hackathon",
    slug: "hackathon",
    name: "浙客松创新实践",
    category: "赛事与成果",
    summary: "以真实问题组织跨学科团队，完成开发、验证和公开展示。",
    detail: "把学习、组队、开发、评审和成果展示连接成一条可观察的实践链路，让能力与项目在短周期中得到验证。",
    audience: "学生团队、命题方与生态伙伴",
    priceBoundary: "具体赛题与规则以当期通知为准",
    imageUrl: tuozheHackathonUrl,
    visibility: "public",
    sortOrder: 2,
    settings: {},
    status: "published",
    version: 1,
  },
  {
    id: "tuozhe-industry",
    slug: "industry-collaboration",
    name: "产业需求与技术转化",
    category: "产业共创",
    summary: "从真实需求出发，推进需求澄清、团队匹配、方案开发、测试与场景验证。",
    detail: "面向企业、学院和项目方组织协作，让成熟项目继续进入真实场景，并形成下一次合作的基础。",
    audience: "企业、学院与真实场景方",
    priceBoundary: "根据需求范围单独评估",
    imageUrl: tuozheHeroUrl,
    visibility: "public",
    sortOrder: 3,
    settings: {},
    status: "published",
    version: 1,
  },
];

export const tuozheCases: CaseStudy[] = [
  {
    id: "tuozhe-case-hackathon",
    slug: "full-stack-ai-hackathon",
    title: "AI 全栈极速黑客松",
    industry: "AI 创新赛事",
    background: "以真实问题为起点，让不同专业的青年人才在短周期内完成协作。",
    solution: "组织跨学科组队、开发验证、阶段评审与成果展示。",
    result: "官网公开资料显示，首届约 300 人报名、100 人正式参赛。",
    clientDisplayName: "浙客松",
    imageUrl: tuozheHackathonUrl,
    visibility: "public",
    sortOrder: 0,
    settings: {},
    status: "published",
    version: 1,
  },
  {
    id: "tuozhe-case-project-plaza",
    slug: "project-plaza",
    title: "项目广场",
    industry: "项目连接与成果展示",
    background: "很多作品在活动结束后缺少持续展示、招募伙伴和推进合作的入口。",
    solution: "用项目卡片呈现项目方向、招募需求、进展与过程记录，让对的人找到项目。",
    result: "让作品被看见，让项目在赛后继续生长。",
    clientDisplayName: "拓浙AI生态",
    imageUrl: tuozhePlatformUrl,
    visibility: "public",
    sortOrder: 1,
    settings: {},
    status: "published",
    version: 1,
  },
  {
    id: "tuozhe-case-learning",
    slug: "future-learning-center",
    title: "未来学习中心 · 智能生命健康",
    industry: "未来学习与医学交叉",
    background: "围绕未来学习场景探索 AI 与生命健康领域的跨学科协作。",
    solution: "连接学习内容、项目实践与医学交叉方向的探索。",
    result: "形成面向未来学习场景的公开项目入口。",
    clientDisplayName: "浙江大学未来学习中心",
    imageUrl: tuozheHeroUrl,
    visibility: "public",
    sortOrder: 2,
    settings: {},
    status: "published",
    version: 1,
  },
];

export const tuozheFaqs: SelectableFaqDocument[] = [
  {
    id: "tuozhe-faq-overview",
    title: "拓浙AI生态是做什么的？",
    answer: "拓浙AI生态连接学生、学院、企业与真实 AI 需求，让机会、学习、项目、赛事和成果进入同一套可持续协作的生态。",
    status: "published",
    visibility: "public",
  },
  {
    id: "tuozhe-faq-student",
    title: "学生可以怎样参与？",
    answer: "可以从官网活动、AI 社区和学习内容开始，再根据基础进入工具练习、项目陪跑、浙客松或企业真实项目。",
    status: "published",
    visibility: "public",
  },
  {
    id: "tuozhe-faq-company",
    title: "企业可以怎样合作？",
    answer: "可以从一个明确的业务问题开始，说明目标、使用对象、数据条件与合规边界，再共同确认团队、方案、周期和验收方式。",
    status: "published",
    visibility: "public",
  },
  {
    id: "tuozhe-faq-hackathon",
    title: "浙客松是什么？",
    answer: "浙客松以真实问题为起点，组织跨学科团队完成开发、验证和公开展示。具体赛题、时间与参与规则以当期官网通知为准。",
    status: "published",
    visibility: "public",
  },
  {
    id: "tuozhe-faq-project",
    title: "项目如何从需求走向落地？",
    answer: "项目从需求澄清开始，经过团队招募、方案设计、开发和测试，最后回到场景方验收；过程与结果会继续沉淀为合作基础。",
    status: "published",
    visibility: "public",
  },
];

export const tuozheInitialBlocks: EnterpriseTemplateBlock[] = [
  {
    id: "identity",
    type: "identity",
    visible: true,
    showTitle: false,
    directoryEnabled: false,
    sortOrder: 0,
    title: "基础名片",
    layoutVariant: "vertical",
    presentation: {
      identityLayout: "vertical",
      background: {
        assetUrl: tuozheHeroUrl,
        fit: "cover",
        position: "center",
        aspectRatio: "4:3",
        focalX: 64,
        focalY: 52,
        scale: 1,
        opacity: 0.32,
        overlay: "dark",
      },
    },
  },
  {
    id: "overview",
    type: "rich_text",
    visible: true,
    showTitle: false,
    directoryEnabled: false,
    sortOrder: 1,
    title: "概览",
    body: "从校园连接真实世界。我们把机会、学习、项目、赛事和成果放进同一条协作路径，让青年人才在真实问题中成长，也让企业与学院更高效地找到团队、验证方案并持续合作。",
  },
  {
    id: "entry",
    type: "action_collection",
    visible: true,
    showTitle: true,
    directoryEnabled: true,
    sortOrder: 2,
    title: "快速了解拓浙",
    actionTemplate: "quick",
    layoutVariant: "auto",
    itemLimit: 4,
    actionItems: [
      { id: "official", title: "官方网站", summary: "了解拓浙AI生态", icon: "external", targetType: "external_url", targetValue: "https://tuotuzju.com/", openMode: "new_tab" },
      { id: "events", title: "活动聚合", summary: "发现讲座、竞赛与招募", icon: "calendar", targetType: "external_url", targetValue: "https://tuotuzju.com/events", openMode: "new_tab" },
      { id: "projects", title: "项目广场", summary: "看项目、找伙伴", icon: "building", targetType: "external_url", targetValue: "https://tuotuzju.com/projects", openMode: "new_tab" },
      { id: "about", title: "关于我们", summary: "了解生态与合作路径", icon: "file", targetType: "external_url", targetValue: "https://tuotuzju.com/about", openMode: "new_tab" },
    ],
  },
  {
    id: "business",
    type: "business_collection",
    visible: true,
    showTitle: true,
    directoryEnabled: true,
    sortOrder: 3,
    title: "生态承接体系",
    productIds: tuozheProducts.map((item) => item.id),
    layoutVariant: "grid",
    itemLimit: 4,
  },
  {
    id: "path",
    type: "rich_text",
    visible: true,
    showTitle: true,
    directoryEnabled: true,
    sortOrder: 4,
    title: "一条可持续的协作路径",
    body: "信息平台负责发布与记录，AI 社区承接学习与组队，浙客松把真实问题带进比赛和实践，成熟项目再进入产业场景验证。每一步都会留下内容、作品和关系，成为下一次合作的基础。",
  },
  {
    id: "cases",
    type: "case_collection",
    visible: true,
    showTitle: true,
    directoryEnabled: true,
    sortOrder: 5,
    title: "正在发生的实践",
    caseIds: tuozheCases.map((item) => item.id),
    layoutVariant: "featured",
    itemLimit: 3,
  },
  {
    id: "gallery",
    type: "image_gallery",
    visible: true,
    showTitle: true,
    directoryEnabled: true,
    sortOrder: 6,
    title: "生态现场",
    imageUrls: [tuozhePlatformUrl, tuozheHackathonUrl, tuozheHeroUrl],
    layoutVariant: "mosaic",
    itemLimit: 3,
    galleryItems: [
      { id: "platform", imageUrl: tuozhePlatformUrl, title: "拓途浙享活动聚合", description: "让校园机会被看见", badgeMode: "title", altText: "拓途浙享活动聚合页面" },
      { id: "hackathon", imageUrl: tuozheHackathonUrl, title: "AI 全栈极速黑客松", description: "跨学科团队完成真实问题验证", badgeMode: "title", altText: "AI 全栈极速黑客松活动现场合影" },
      { id: "ecosystem", imageUrl: tuozheHeroUrl, title: "人才、技术与产业连接", description: "持续形成下一次合作", badgeMode: "title", altText: "校园与产业生态连接概念图" },
    ],
  },
  {
    id: "faq",
    type: "faq",
    visible: true,
    showTitle: true,
    directoryEnabled: true,
    sortOrder: 7,
    title: "常见问题",
    faqMode: "all_published",
    faqDocumentIds: [],
    itemLimit: 5,
  },
  {
    id: "trust",
    type: "trust_panel",
    visible: true,
    showTitle: true,
    directoryEnabled: true,
    sortOrder: 8,
    title: "资料说明",
    body: "本名片内容根据 tuotuzju.com 当前公开资料整理；活动安排、合作关系与参与规则请以官网最新发布为准。",
  },
  {
    id: "contact",
    type: "cta",
    visible: true,
    showTitle: true,
    directoryEnabled: true,
    sortOrder: 9,
    title: "从一个真实问题开始",
    body: "无论是 AI 场景验证、联合赛题、项目共建还是青年人才合作，都可以先从一个明确的问题与边界开始。",
    ctaLabel: "访问拓浙官网",
    ctaUrl: "https://tuotuzju.com/",
    ctaIcon: "external",
  },
  {
    id: "assistant",
    type: "ai_assistant",
    visible: true,
    showTitle: true,
    directoryEnabled: true,
    sortOrder: 10,
    title: "拓浙 AI 资料助手",
    body: "询问生态业务、学生参与、项目实践、浙客松或企业合作方式；回答以已审核公开资料为边界。",
  },
];
